#!/bin/sh

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
mvim -u $HOME/.vimrc.bundles +PlugInstall +PlugClean! +qa
rm ~/.bashrc
echo "installing oh-my-zsh.git ..."
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
echo "please: chsh -s /bin/zsh"
echo "please: add files to ~/Library/Dictionaries"
echo "installing hammerspoon.git config ..."
git clone https://github.com/zzuse/hammerspoon.git ~/.hammerspoon
echo "please: npm -g install cloc"
echo "mkdir -p .tmux/plugins/"
mkdir -p ~/.tmux/plugins/
cd ~/.tmux/plugins/
git clone https://github.com/tmux-plugins/tpm
git clone https://github.com/tmux-plugins/tmux-sensible
git clone https://github.com/tmux-plugins/tmux-yank
echo "tmux done"
