#!/bin/sh

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
~/dotfiles/install_tmux.sh
vim -u $HOME/.vimrc.bundles +PlugInstall +PlugClean! +qa
rm -rf ~/.config/nvim
git clone https://github.com/zzuse/nvim_config.git ~/.config/nvim
case `uname` in
  Darwin)
    # xargs -n1 code --install-extension < ~/.vscode-extensions.txt
    echo "link VSCode settings..."
    rm ~/Library/Application\ Support/Code/User/settings.json
    ln -s ~/.vscode-settings.json ~/Library/Application\ Support/Code/User/settings.json
    echo "link Rime settings..."
    rm ~/Library/Rime/default.custom.yaml
    ln -s ~/.default.custom.yaml ~/Library/Rime/default.custom.yaml
    echo "installing hammerspoon.git config ..."
    git clone https://github.com/zzuse/hammerspoon.git ~/.hammerspoon
    echo "PLEASE: add files to ~/Library/Dictionaries"
    rm ~/.zshrc-Brain ~/.zshrc-VM ~/.bashrc
  ;;
  Linux)
    rm ~/.zshrc-Brain ~/.zshrc-Darwin ~/.zshrc-VM ~/.tmux-Darwin.conf ~/.bashrc
  ;;
esac
echo "installing oh-my-zsh.git ..."
git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
echo "mkdir -p .tmux/plugins/"
mkdir -p ~/.tmux/plugins/
#echo "installing tmux plugins..."
#cd ~/.tmux/plugins/
#git clone https://github.com/tmux-plugins/tpm
#git clone https://github.com/tmux-plugins/tmux-sensible
#git clone https://github.com/tmux-plugins/tmux-yank
echo "installing zsh-autosuggestions ..."
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
echo "installing zsh-syntax-highlighting ..."
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git  ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
echo "installing zsh-auto-notify..."
git clone https://github.com/MichaelAquilina/zsh-auto-notify.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/auto-notify
echo "installing p10k..."
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
